export const LawyerList = [
	{
		user_id: 71,
		name: "吴涛-71",
		law_firm_name: "东方律师事务所",
		addr: "重庆市渝中区解放碑步行街1号",
		expertise: "劳动争议",
		grade_name: "主办律师",
		license_no: "https://example.com/cy/20250010.jpg",
		lawyer_license_id: "11658217365612412",
		intro: "擅长集体劳动争议、裁员方案设计及劳资谈判。",
		practice_years: 8,
		case_count: 1,
		rating: 4.8,
		id: 10,
		online: true
	},
	{
		user_id: 91,
		name: "陈宇-91",
		law_firm_name: "湖南金州律师事务所",
		addr: "中国湖南省长沙市芙蓉区五一大道99号",
		expertise: "劳动争议、工伤赔偿",
		grade_name: "高级合伙人",
		license_no: "https://static.example.com/license/pro_36.jpg",
		lawyer_license_id: "13026376166191961",
		intro: "在工伤认定、劳动能力鉴定及赔偿谈判方面经验丰富，多次为职工争取到高于保险公司初步方案的赔偿结果。",
		practice_years: 16,
		case_count: 2,
		rating: 4.1,
		id: 44,
		online: true
	},
	{
		user_id: 92,
		name: "周静-92",
		law_firm_name: "华北律师事务所",
		addr: "天津市和平区南京路200号",
		expertise: "劳动争议",
		grade_name: "专职律师",
		license_no: "https://example.com/cy/20250009.jpg",
		lawyer_license_id: "92046526997559559",
		intro: "专注劳动合同、加班工资、工伤赔偿等劳动争议案件。",
		practice_years: 7,
		case_count: 1,
		rating: 4,
		id: 9,
		online: true
	},
	{
		user_id: 93,
		name: "孙浩-93",
		law_firm_name: "恒信律师事务所",
		addr: "武汉市武昌区中北路98号",
		expertise: "劳动争议",
		grade_name: "资深律师",
		license_no: "https://example.com/cy/20250012.jpg",
		lawyer_license_id: "63736959912885281",
		intro: "多年办理劳动仲裁和诉讼案件，熟悉劳动立法与司法实践。",
		practice_years: 10,
		case_count: 1,
		rating: 3.6,
		id: 12,
		online: false
	},
	{
		user_id: 94,
		name: "郑丽-94",
		law_firm_name: "锦绣律师事务所",
		addr: "成都市锦江区红星路三段88号",
		expertise: "劳动争议",
		grade_name: "专职律师",
		license_no: "https://example.com/cy/20250011.jpg",
		lawyer_license_id: "93087415268599840",
		intro: "兼顾劳动争议处理与企业合规管理，为多家大型企业提供人力资源合规服务。",
		practice_years: 6,
		case_count: 1,
		rating: 3,
		id: 11,
		online: false
	},
	{
		user_id: 95,
		name: "郑丽-95",
		law_firm_name: "锦绣律师事务所",
		addr: "成都市锦江区红星路三段88号",
		expertise: "劳动争议",
		grade_name: "专职律师",
		license_no: "https://example.com/cy/20250011.jpg",
		lawyer_license_id: "93087415268599840",
		intro: "兼顾劳动争议处理与企业合规管理，为多家大型企业提供人力资源合规服务。",
		practice_years: 6,
		case_count: 1,
		rating: 3,
		id: 11,
		online: false
	}
];
