export const fxzxiconfont = {
	"fxzh-caidan": "e648",
	"fxzh-caidan1": "e668",
	"fxzh-fudongcaidan": "e66f",
	"fxzh-caidan2": "e606",
	"fxzh-caidan3": "e608",
	"fxzh-caidan4": "e60e",
	"fxzh-falvfagui": "e60b",
	"fxzh-suyaniconchanpinleibufenzuodaohangbufen85-copy": "e740",
	"fxzh-wangluo": "e617",
	"fxzh-falvfagui1": "e630",
	"fxzh-network-layout": "e9fc",
	"fxzh-a-fagui1": "e88c",
	"fxzh-saying": "e62f",
	"fxzh-yuyin": "e6f6",
	"fxzh-yuyin1": "e66c",
	"fxzh-dakaijianpan": "e619",
	"fxzh-hulianwang": "e607",
	"fxzh-jianpan": "e61c",
	"fxzh-wangzhan": "e6f5",
	"fxzh-jianpan1": "e65f",
	"fxzh-jianpan2": "ed15",
	"fxzh-zhishiku10": "ea4e",
	"fxzh-zhishiku": "e60a"
};
