// 自动根据后端提供的错误码表整理的默认提示文案
// 仅用于前端兜底提示；如果后端返回了明确的 message，则以 message 为准

export const ERROR_DEFAULT_MESSAGE: Record<string, string> = {
	"Admin.User.InvalidType": "非法的用户类型",
	"Admin.User.NoChanges": "未提供可更新字段",
	"Chat.Token.InvalidUserId": "缺少有效的用户 ID",
	HTTPException: "请求异常",
	"Law.Consult.Empty": "咨询内容不能为空",
	"Law.Doc.MissingContent": "缺少 content",
	"Law.Summary.MissingContent": "缺少 content",
	"Lawyer.Review.InvalidAction": "非法的审核动作",
	"Lawyer.Review.MissingReason": "拒绝申请时必须填写原因",
	"Lawyer.Sms.SceneInvalid": "不支持的短信场景",
	"Lawyer.SmsCode.Invalid": "短信验证码错误或已过期",
	"User.Profile.NoChanges": "未提供可更新的字段",
	"User.Register.MissingPhone": "请输入手机号",
	"User.Sms.SceneInvalid": "不支持的短信场景",
	"User.Sms.TooFrequent": "发送频率过高，请稍后重试",
	"User.SmsCode.Invalid": "请正确输入验证码",
	"User.Credentials.Invalid": "请正确输入手机号、密码",
	"User.Token.Invalid": "Token is invalid or expired",
	"Admin.PermissionDenied": "无权限访问",
	"Admin.User.NotFound": "用户不存在",
	"Lawyer.Info.NotFound": "尚未提交律师认证",
	"Question.NotFound": "问题不存在",
	"User.Login.PhoneNotFound": "手机号未注册",
	"User.Message.NotFound": "记录不存在",
	"User.Message.UserNotFound": "用户不存在",
	"User.Profile.NotFound": "用户不存在",
	"Admin.User.PhoneExists": "手机号已存在",
	"User.Register.PhoneExists": "手机号已注册",
	"Request.ValidationError": "请求参数校验失败",
	"Law.Consult.Unavailable": "服务暂时不可用",
	"Lawyer.Recommend.RedisError": "推荐失败，缓存访问异常",
	"User.Message.ParseError": "消息解析失败",
	"User.Message.RedisError": "消息保存失败",
	"User.Register.Unknown": "注册失败，请稍后重试",
	"User.Sms.RedisError": "验证码生成失败",
	"AliVoice.Token.InvalidResponse": "阿里云返回了非法的 JSON",
	"AliVoice.Token.MissingField": "响应中缺少 Token 字段",
	"AliVoice.Token.RequestFailed": "阿里云语音 Token 获取失败",
	"AliVoice.Token.Unknown": "获取语音 Token 失败",
	"Aliyun.STS.Failed": "获取阿里云 STS 凭证失败",
	"User.Sms.SendFailed": "发送失败，请稍后重试"
};
